image: WMF 5

branches:
    only:
        - main

environment:
  PSGalleryAPIKey:
    secure: IES4nPv8KGnfnJ1qw+9EZA8nEbaq/7FrxhLnv5L1I4HFypBMAdqXpj7x7OQBNUSN

build:
  verbosity: detailed

build_script:
  - ps: . .\build.ps1
